### ISSUE TITLE
Launch pad Pro MK3 doesn´t works

### ISSUE THREAD

**Issue by Pitrakos** [TheKikGen/MPCLiveXplore-libs#7]
Just tryed with a launchpad Pro MK3 using LPPROMK3 sentence in doer_list and doesn´t works, Launchpad Pro MK3 is not detected.

It seems there is a driver for LP PRO MK3 in bootstrap modules with the name LPPROMK3 which I used. 

With my LP Mini MK3 it works perfect using LPMK3 and driver is loaded and working perfectly.

Is there  somenthing I´m missing for have LP PRO MK3 working? maybe somenthing to configure in Launch Pad?

I think extra buttons in Pro MK3  could be great and more close to real Force.

Thanks

**Comment by TheKikGen** [comment]
Hi.  As I haven't the MK3 pro, it is not easy to debug.  I deduced most of the command from the developer manual and the LP mini.  I will check that when 'i'll have time !

**Comment by Pitrakos** [comment]
Thank you very much!!!

Hope to see an update soon for MK3 pro!.

Regards

**Comment by TheKikGen** [comment]
Bug correction done !  Midi name was incorrect "Mk3" instead of "MK3". The first form is used for the Launchpad mini Mk3...
You need to update with the update script.  Look here : https://github.com/TheKikGen/MPCLiveXplore-libs/wiki#updating-an-existing-bootstrap-installation

**Comment by Pitrakos** [comment]
Thanks, tryed updated as you point to me, but after update is done and restart, doesn´t load IamForce, go to directly to MPC OS.

Tryed to edit doer-list but everything looks correct. I must to burn img file to the pen drive  to access again to Iamforce2.

Thank you
